# Generated by Django 6.0 on 2026-01-03 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated unique ID (e.g., IST-2025-001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Full name of article author", max_length=255
                    ),
                ),
                (
                    "author_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email for communication & status updates",
                        max_length=254,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        choices=[
                            (1, "Start"),
                            (2, "Enter Metadata"),
                            (3, "Upload Submission"),
                            (4, "Suggestive Reviewers"),
                            (5, "Confirmation"),
                            (6, "Next Steps"),
                        ],
                        default=1,
                        help_text="Current step (1-6) in submission process",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (In Progress)"),
                            ("SUBMITTED", "Submitted (Completed)"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="DRAFT = in progress, SUBMITTED = completed",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="True after Step 6 (prevents editing)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When submission was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When submitted (Step 6 completed)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission_id"], name="submissions_submiss_762296_idx"
                    ),
                    models.Index(
                        fields=["author_email"], name="submissions_author__9d0bed_idx"
                    ),
                    models.Index(
                        fields=["status"], name="submissions_status_c2b4f2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_be6fdb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubmissionStep1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step1_comments",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments for the editor",
                        null=True,
                    ),
                ),
                (
                    "agrees_to_copyright",
                    models.BooleanField(
                        default=False, help_text="User agrees to copyright terms"
                    ),
                ),
                (
                    "agrees_to_privacy",
                    models.BooleanField(
                        default=False, help_text="User agrees to privacy policy"
                    ),
                ),
                (
                    "agrees_to_policies",
                    models.BooleanField(
                        default=False, help_text="User agrees to submission policies"
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When step 1 was saved"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="Link to main submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step1",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Step 1",
                "verbose_name_plural": "Submission Steps 1",
            },
        ),
        migrations.CreateModel(
            name="SubmissionStep2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title (5-300 characters)", max_length=300
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        help_text="Article abstract (150-200 words recommended)"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Keywords separated by commas (e.g., AI, Machine Learning, Neural Networks)",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "ai",
                                "Artificial Intelligence and Machine Learning (AI/ML)",
                            ),
                            ("architecture", "Architecture and Architectural Design"),
                            ("basic", "Basic Sciences & Mathematics"),
                            ("biomedical", "Biomedical Sciences and Bioengineering"),
                            ("business", "Business Sciences"),
                            ("cs", "Computer Science"),
                            ("data", "Data Sciences"),
                            ("economics", "Economics"),
                            ("engineering", "Engineering and Technology"),
                            ("management", "Management"),
                        ],
                        help_text="Article category",
                        max_length=20,
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When step 2 was saved"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="Link to main submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step2",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Step 2",
                "verbose_name_plural": "Submission Steps 2",
            },
        ),
        migrations.CreateModel(
            name="SubmissionStep3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("docx", "Word Document"),
                            ("rtf", "Rich Text Format"),
                        ],
                        help_text="PDF, DOCX, or RTF",
                        max_length=10,
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        help_text="Path in Supabase Storage (e.g., submissions/IST-001/file.pdf)",
                        max_length=500,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When file was uploaded"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Link to main submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step3_files",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission File",
                "verbose_name_plural": "Submission Files",
            },
        ),
        migrations.CreateModel(
            name="SubmissionStep5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_agrees_copyright",
                    models.BooleanField(
                        default=False, help_text="Final copyright agreement"
                    ),
                ),
                (
                    "final_agrees_privacy",
                    models.BooleanField(
                        default=False, help_text="Final privacy agreement"
                    ),
                ),
                (
                    "confirms_submission",
                    models.BooleanField(
                        default=False, help_text="User confirms ready to submit"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When step 5 was confirmed"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="Link to main submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step5",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Step 5",
                "verbose_name_plural": "Submission Steps 5",
            },
        ),
        migrations.CreateModel(
            name="SubmissionStep4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewer_number",
                    models.IntegerField(
                        choices=[(1, "Reviewer 1"), (2, "Reviewer 2")],
                        help_text="1 or 2",
                    ),
                ),
                (
                    "reviewer_prefix",
                    models.CharField(
                        choices=[
                            ("Dr", "Dr."),
                            ("Prof", "Prof."),
                            ("Mr", "Mr."),
                            ("Ms", "Ms."),
                        ],
                        help_text="Dr, Prof, Mr, or Ms",
                        max_length=10,
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        help_text="Full name of suggested reviewer", max_length=255
                    ),
                ),
                (
                    "reviewer_email",
                    models.EmailField(
                        help_text="Reviewer email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "reviewer_department",
                    models.CharField(
                        help_text="Department/Institute of reviewer", max_length=200
                    ),
                ),
                (
                    "reviewer_affiliation",
                    models.CharField(
                        help_text="University/Organization of reviewer", max_length=200
                    ),
                ),
                (
                    "suggested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When reviewer was suggested"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Link to main submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step4_reviewers",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggested Reviewer",
                "verbose_name_plural": "Suggested Reviewers",
                "unique_together": {("submission", "reviewer_number")},
            },
        ),
    ]
