# Generated by Django 6.0 on 2026-01-04 02:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the author/reviewer",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "affiliation",
                    models.CharField(
                        help_text="University, institution, or organization",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department (for reviewers)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Main Author"),
                            ("co-author", "Co-Author"),
                            ("reviewer", "Reviewer"),
                        ],
                        default="author",
                        help_text="Author's role in the submission process",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dr", "Dr."),
                            ("Prof", "Prof."),
                            ("Mr", "Mr."),
                            ("Ms", "Ms."),
                        ],
                        help_text="Professional title (for reviewers)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["email"], name="submissions_email_f7114d_idx"),
                    models.Index(fields=["role"], name="submissions_role_cb56d5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number (optional)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("paper_submission", "Paper Submission"),
                            ("general_inquiry", "General Inquiry"),
                            ("buy_journal", "Buy Journal or Book"),
                        ],
                        help_text="Inquiry subject",
                        max_length=30,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message content",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether admin has read this message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject"], name="submissions_subject_a208f9_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="submissions_is_read_db4d44_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_179c87_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated submission identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "corresponding_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Author wishes to be contacted about this submission",
                    ),
                ),
                (
                    "copyright_agreed",
                    models.BooleanField(
                        default=False, help_text="Author agrees to copyright terms"
                    ),
                ),
                (
                    "privacy_agreed",
                    models.BooleanField(
                        default=False, help_text="Author agrees to privacy policy"
                    ),
                ),
                (
                    "editor_comments",
                    models.TextField(
                        blank=True, help_text="Comments for the editor", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title (min 10 chars, max 300)",
                        max_length=300,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        help_text="Abstract (150-200 words recommended)",
                        validators=[django.core.validators.MinLengthValidator(150)],
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Keywords (comma-separated, 4-6 recommended)",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "ai",
                                "Artificial Intelligence and Machine Learning (AI/ML)",
                            ),
                            ("architecture", "Architecture and Architectural Design"),
                            ("basic", "Basic Sciences & Mathematics"),
                            ("biomedical", "Biomedical Sciences and Bioengineering"),
                            ("business", "Business Sciences"),
                            ("cs", "Computer Science"),
                            ("data", "Data Sciences"),
                            ("economics", "Economics"),
                            ("engineering", "Engineering and Technology"),
                            ("management", "Management"),
                        ],
                        help_text="Article category",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revisions_requested", "Revisions Requested"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Current status of the submission",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (admin only)", null=True
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the submission was finalized",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "co_authors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Co-authors (max 4)",
                        related_name="submissions_as_co_author",
                        to="submissions.author",
                    ),
                ),
                (
                    "main_author",
                    models.ForeignKey(
                        help_text="Corresponding/main author",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions_as_main_author",
                        to="submissions.author",
                    ),
                ),
                (
                    "reviewer_1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary suggested reviewer",
                        limit_choices_to={"role": "reviewer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions_as_reviewer_1",
                        to="submissions.author",
                    ),
                ),
                (
                    "reviewer_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secondary suggested reviewer (optional)",
                        limit_choices_to={"role": "reviewer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions_as_reviewer_2",
                        to="submissions.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("pending", "Pending Response"),
                        ],
                        default="pending",
                        help_text="Review status",
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Reviewer comments", null=True
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ],
                        help_text="Review rating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        blank=True, help_text="When reviewer was invited", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Review due date", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Reviewer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="submissions.author",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Associated submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer",
                "verbose_name_plural": "Reviewers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Manuscript file",
                        upload_to="submissions/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "rtf"],
                                message="Only PDF, DOC, DOCX, and RTF files are allowed",
                            )
                        ],
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Microsoft Word"),
                            ("docx", "Microsoft Word (DOCX)"),
                            ("rtf", "Rich Text Format"),
                        ],
                        help_text="File type (auto-detected)",
                        max_length=10,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Associated submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission File",
                "verbose_name_plural": "Submission Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Submission Created"),
                            ("updated", "Submission Updated"),
                            ("submitted", "Submission Submitted"),
                            ("status_changed", "Status Changed"),
                            ("file_added", "File Added"),
                            ("file_removed", "File Removed"),
                            ("reviewer_assigned", "Reviewer Assigned"),
                            ("review_completed", "Review Completed"),
                            ("email_sent", "Email Sent"),
                            ("comment_added", "Comment Added"),
                        ],
                        help_text="Action performed",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of action",
                        null=True,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="User who performed the action",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Associated submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Log",
                "verbose_name_plural": "Submission Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["-submitted_at"], name="submissions_submitt_1f3aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_c2b4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["category"], name="submissions_categor_2bffe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["main_author"], name="submissions_main_au_fd05f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewer",
            index=models.Index(
                fields=["submission"], name="submissions_submiss_2412a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewer",
            index=models.Index(fields=["status"], name="submissions_status_9bd42f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewer",
            unique_together={("submission", "author")},
        ),
        migrations.AddIndex(
            model_name="submissionfile",
            index=models.Index(
                fields=["submission"], name="submissions_submiss_3cedac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionfile",
            index=models.Index(
                fields=["file_type"], name="submissions_file_ty_38c081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionlog",
            index=models.Index(
                fields=["submission"], name="submissions_submiss_2e0938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionlog",
            index=models.Index(fields=["action"], name="submissions_action_3c68f7_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionlog",
            index=models.Index(
                fields=["-timestamp"], name="submissions_timesta_7c93d8_idx"
            ),
        ),
    ]
