# Generated by Django 4.2.7 on 2026-01-04 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template identifier (e.g., submission_confirmation)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION_CONFIRMATION", "User Submission Confirmation"),
                            ("ADMIN_NOTIFICATION", "Admin New Submission Alert"),
                            ("REVIEW_UPDATE", "Review Status Update"),
                            ("ACCEPTANCE", "Paper Accepted"),
                            ("REJECTION", "Paper Rejected"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("CONTACT_REPLY", "Contact Form Reply"),
                            ("WELCOME", "Welcome Email"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject with variables like {submission_id}, {author_name}",
                        max_length=200,
                    ),
                ),
                (
                    "body_html",
                    models.TextField(help_text="HTML email body with variables"),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True, help_text="Plain text fallback", null=True
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Available template variables",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_type", "is_active"],
                        name="emails_emai_email_t_239f7d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="emails_emai_created_6c254c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        default="noreply@istpublications.com", max_length=254
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("email_type", models.CharField(db_index=True, max_length=50)),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent Successfully"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failed_reason",
                    models.TextField(
                        blank=True, help_text="Error message if email failed", null=True
                    ),
                ),
                (
                    "read_count",
                    models.IntegerField(
                        default=0, help_text="Number of times email was opened"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emails.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="emails_emai_status_0b5614_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "status"],
                        name="emails_emai_recipie_29ee31_idx",
                    ),
                    models.Index(
                        fields=["email_type", "status"],
                        name="emails_emai_email_t_766796_idx",
                    ),
                    models.Index(
                        fields=["submission_id", "status"],
                        name="emails_emai_submiss_e07d37_idx",
                    ),
                ],
            },
        ),
    ]
