# Generated by Django 6.0 on 2025-12-27 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the person", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Valid email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("paper_submission", "Paper Submission"),
                            ("general_inquiry", "General Inquiry"),
                            ("buy_journal", "Buy Journal or Book"),
                        ],
                        help_text="Reason for contacting",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Message content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
